### ISSUE TITLE
Decide the name of the actual name of the code cmd

### ISSUE THREAD

**Issue by aflashyrhetoric** [aflashyrhetoric/backlog-cli#8]

**Comment by aflashyrhetoric** [comment]
@yenchieh What do you think? I was thinking we can just make it `bl` maybe. So it's short to type. It looks like there's no package on homebrew with the name `bl`. 

`bl add pr` or `bl pr` could be an example usage. 

BTW: Happy birthday! :tada:

**Comment by yenchieh** [comment]
@aflashyrhetoric it sounds good. Thank you!

**Comment by aflashyrhetoric** [comment]
I will use `blg` for now, I think it'll be okay
